### ISSUE TITLE
Really thrilled about this repo!

### ISSUE THREAD

**Issue by DanielTimLee** [erikbrinkman/d3-dag#1]
I was just trying to implement `dag` graphs in my project with `dagre` and at the moment, 
realized that it isn't maintained anymore and concerned with using it in my project.

> This currently wraps dagre, but I'd prefer to reimplement a DAG layout to not require it as a dependency, and to allow more options about the different phases of DAG layout. This would be a good place to start. Ideally each phase will just be a callback, similar to the way other d3 layouts are done.

And really thrilled it'll be reimplemented without `darge` project.
Looking forward to heavily using in my project!

Cheers! 👍

**Comment by erikbrinkman** [comment]
This is now essentially feature complete, and renders entirely without dagre.
