### ISSUE TITLE
Specific key order appears to cause decrossOpt to hang

### ISSUE THREAD

**Issue by g-sam** [erikbrinkman/d3-dag#107]
Please see this pen: https://codepen.io/g-sam/pen/abqMqbg

There are two json objects, `fast` and `slow`, containing the same nodes in a different order. If you construct the layout on line 1871 with `fast`, everything renders fine. If you construct it with `slow` the browser will freeze. In our app the calculation does actually finish after 5-10 minutes although codepen appears to refresh before this happens.

The problem does not occur when using `decrossTwoLayer`.

**Comment by g-sam** [comment]
It's beyond my expertise to comment on your suggestions but I have a tangential suggestion: since it's so hard to predict when `decrossOpt` might run into difficulties it really shouldn't be used without being wrapped in a timeout mechanism. I didn't really appreciate this as it was finishing very quickly on our other graphs of similar size/complexity. Perhaps a way to gracefully timeout and fall back to `decrossTwoLayer` should be included in the lib.

**Comment by erikbrinkman** [comment]
it actually does have a [timeout mechanism](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_decross_opt.OptOperator.html#large)! Unfortunately I think in the current version the heuristic is off. In an update version it should be better able to predict timeout issues.

Sorry that you had to be hit with a case that bypassed the check. I will use this an example to make sure it appropriately errors on this as input.

Ideally for graphs like this, an exception will be raised, and if you wanted to backoff, you could catch this exception and switch to a different layout, or even write a custom decross operator that tried opt, and used twolayer if it times out.

**Comment by erikbrinkman** [comment]
The prerelease version updates this codes to check the actual number of variables, which should be better at catching this inconsistency:

https://github.com/erikbrinkman/d3-dag/blob/f3f0f20dfc0b658bfcd09225667e2da68d2f19b2/src/sugiyama/decross/opt.ts#L378-L384

The downside is is creates the program which might be very large. It's possible to compute these sizes in advance, but the code was quite messy, so I opted for this simpler version.

Don't hesitate to reopen if it's not addressed.
