### ISSUE TITLE
What are the size limits on graphs? Can't layout 39-node graph

### ISSUE THREAD

**Issue by zfrenchee** [erikbrinkman/d3-dag#14]
I forked the first example:
https://beta.observablehq.com/@bumbeishvili/d3-dag-vert

And just changed the data to my graph with 39 nodes. 
https://beta.observablehq.com/@zfrenchee/d3-dag-vert

Which basically freezes -- eats up all my CPU and can't layout the nodes. 

There are no cycles in my graph, and I can `d3.dratify()(graph)` without a problem. Why does the layout struggle so much with my graph? 

Here's the graph for reference: 
```
[{"id":"GO:0005575"},
 {"id":"GO:1903561","parentIds":["GO:0031982","GO:0043230"]},
 {"id":"GO:0005737","parentIds":["GO:0044424"]},
 {"id":"GO:0030666","parentIds":["GO:0030139","GO:0030659","GO:0098588","GO:0098805"]},
 {"id":"GO:0043230","parentIds":["GO:0043226","GO:0044421"]},
 {"id":"GO:0005623","parentIds":["GO:0005575"]},
 {"id":"GO:0005938","parentIds":["GO:0071944","GO:0099568"]},
 {"id":"GO:0031982","parentIds":["GO:0043227"]},
 {"id":"GO:0099568","parentIds":["GO:0005737","GO:0044444"]},
 {"id":"GO:0097708","parentIds":["GO:0031982","GO:0043229"]},
 {"id":"GO:0005622","parentIds":["GO:0044464"]},
 {"id":"GO:0016020","parentIds":["GO:0005575"]},
 {"id":"GO:0043226","parentIds":["GO:0005575"]},
 {"id":"GO:0030055","parentIds":["GO:0030054"]},
 {"id":"GO:0005576","parentIds":["GO:0005575"]},
 {"id":"GO:0030054","parentIds":["GO:0005575"]},
 {"id":"GO:0031410","parentIds":["GO:0044444","GO:0097708"]},
 {"id":"GO:0031090","parentIds":["GO:0016020","GO:0043227","GO:0044422"]},
 {"id":"GO:0030139","parentIds":["GO:0031410"]},
 {"id":"GO:0070062","parentIds":["GO:0005615","GO:1903561"]},
 {"id":"GO:0044464","parentIds":["GO:0005575","GO:0005623"]},
 {"id":"GO:0005925","parentIds":["GO:0005924"]},
 {"id":"GO:0044444","parentIds":["GO:0005737","GO:0044424"]},
 {"id":"GO:0044421","parentIds":["GO:0005575","GO:0005576"]},
 {"id":"GO:0012506","parentIds":["GO:0031090","GO:0031982"]},
 {"id":"GO:0098805","parentIds":["GO:0016020"]},
 {"id":"GO:0005615","parentIds":["GO:0044421"]},
 {"id":"GO:0098588","parentIds":["GO:0031090"]},
 {"id":"GO:0044433","parentIds":["GO:0031410","GO:0044444","GO:0044446"]},
 {"id":"GO:0043227","parentIds":["GO:0043226"]},
 {"id":"GO:0005912","parentIds":["GO:0070161"]},
 {"id":"GO:0044422","parentIds":["GO:0005575","GO:0043226"]},
 {"id":"GO:0070161","parentIds":["GO:0030054"]},
 {"id":"GO:0030659","parentIds":["GO:0012506","GO:0044433"]},
 {"id":"GO:0043229","parentIds":["GO:0043226","GO:0044424"]},
 {"id":"GO:0044424","parentIds":["GO:0005622","GO:0044464"]},
 {"id":"GO:0044446","parentIds":["GO:0043229","GO:0044422","GO:0044424"]},
 {"id":"GO:0071944","parentIds":["GO:0044464"]},
 {"id":"GO:0005924","parentIds":["GO:0005912","GO:0030055"]}
];
```

**Comment by erikbrinkman** [comment]
Hey @zfrenchee,

This is the second time someone has had this issue. The default configuration for dratify are meant to maximize prettiness over speed. Unfortunately, part of that is a crossing minimization step that's an NP-complete MILP, e.g. can take a very long time to solve.

In the readme there's an example for doing this "fast." I would recommend trying that. It should run reasonably fast.

Given that you're the second person to have this issue (and report it), I think it makes sense to change the defaults to be fast, and allow people to opt in to more expensive layouts. This may require some tweaks to make the fast layouts a bit better by default.

**Comment by zfrenchee** [comment]
Thanks for getting back, @erikbrinkman. After opening this issue, I also saw #11 and changed the options to be the fastest which you list, but it still freezes. Can you verify that my graph is un-renderable even with the "fastest" options?

**Comment by erikbrinkman** [comment]
I put your data into [this fiddle](https://jsfiddle.net/x9kb5v4a/) and it rendered almost instantly on my computer. Are you seeing or doing something different?

**Comment by zfrenchee** [comment]
@erikbrinkman your fiddle is rendering properly for me. That's odd -- is this an issue with Observable then?

**Comment by erikbrinkman** [comment]
Presumably? I'm not very familiar with Observable. Can you post a link with a version that's not working?

**Comment by erikbrinkman** [comment]
That link uses expensive layout algorithms, unlike the fiddle which uses the fast ones. See the difference between the normal and fast examples.

**Comment by erikbrinkman** [comment]
This should be resolved now that the default decrossing algorithm defaults to fast two layer, and there are more examples on the readme.
