### ISSUE TITLE
Support for nodes and links metadata

### ISSUE THREAD

**Issue by Fed03** [erikbrinkman/d3-dag#16]
Hi! Is it possible to attach metadata to nodes and links?
Something like
```json
{
  "id": 1,
  "data": {
    "name": "john",
    "age": 28
  },
  "children": [
    {
      "linkData": {
        "text": "marriage"
      },
      "node": {
        "id": 2,
        "data": {
          "name": "jane",
          "age": 32
        }
      }
    },
    {
      "linkData": {
        "text": "son"
      },
      "node": {
        "id": 3,
        "data": {
          "name": "jack",
          "age": 3
        }
      }
    }
  ]
}
```

or analogous for stratify?

**Comment by erikbrinkman** [comment]
Unfortunately it's not.  The easiest thing to do would to be to store it in the node's metadata and then set it after creation.

However, this seems like a useful ability, and it shouldn't be too challenging. I'll try to fix it in the next week or so.

**Comment by Fed03** [comment]
First class!
