### ISSUE TITLE
Arrow example does not work with 0.2.3

### ISSUE THREAD

**Issue by andreapier** [erikbrinkman/d3-dag#17]
Hi, I updated to `v0.2.3` and noticed that the arrow calculation stopped working.  
I updated the online example to make it run:
- import `grafo.json` from examples folder
- use `dagStratify` instead of `dratify`  

[This is the updated link](https://jsfiddle.net/5jg7rdy9/)  
  
However the arrow are always placed at the top left corner.  
I suspect that the position calculation is somehow changed as `links` are now provided at creation time.  
Can you please update the example to make it actually work as with `v0.1.x`?  
Thanks a lot!

**Comment by erikbrinkman** [comment]
Thanks for doing this. I got lazy when I updated to 2.0. I think the change is the fact that edges now include the end points, so that probably just needs to be fixed. I'll hopefully get to this this weekend.

**Comment by andreapier** [comment]
That would be very nice of you, thanks.
