### ISSUE TITLE
Comma Dangle eslint rule 

### ISSUE THREAD

**Issue by mattsibs** [erikbrinkman/d3-dag#19]
Hi,

I am using your library in an angular project and the eslint comma dangle rule is causing issues with the angular build.

The following issue is
ERROR in main.81d528981f082d6185f9.js from Terser
Unexpected token: punc ()) [main.81d528981f082d6185f9.js:188447,4]

One of the places the issue is found is in src/sugiyama/coord/center.js line 12

I have a commit that applies this rule across the code base. Would you allow me to become a contributor so that I can push my changes to a branch

Regards
Matthew

**Comment by erikbrinkman** [comment]
I've discussed this in email, but why don't you submit a PR. MAke sure you tag it with `closes #19`
