### ISSUE TITLE
Support for vertical Zherebko

### ISSUE THREAD

**Issue by Qu4tro** [erikbrinkman/d3-dag#21]
Hello there.

Would you consider adding a vertical zherebko render method? My use-case involves a topological sort and a >100 node graph.

It's great that zherebko renders them sorted, but I feel it would be a pain to horizontal scroll through everything.

**Comment by erikbrinkman** [comment]
In general, the layouts are all vertical in their design, but it's not hard to flip them by just swapping x and y coordinates. In the example in the documentation you'll see the following code snippet:

```
  const line = d3.line()
    .curve(d3.curveMonotoneX)
    .x(d => d.y)
    .y(d => d.x);
```

where I transpose it to make the layout horizontal. I'm going to close this out, but feel free to reopen if I'm missing something.
