### ISSUE TITLE
`javascript-lp-solver` should be lock to 0.4.5

### ISSUE THREAD

**Issue by marswong** [erikbrinkman/d3-dag#25]
`javascript-lp-solver` over `0.4.5` add `External` module which requires node internal `fs` and `child_process` leads to the compilation error of `webpack` projects

**Comment by erikbrinkman** [comment]
It seems that this was only added `0.4.20`, so I'm going to peg at `0.4.17` for the short term

**Comment by erikbrinkman** [comment]
Also @marswong PRs are welcome if you want to add some automated test to make sure webpack works
