### ISSUE TITLE
Is there a React package we can use?

### ISSUE THREAD

**Issue by vaastav** [erikbrinkman/d3-dag#30]
If not, I was wondering how would we integrate d3-dag in React?

**Comment by znicholasbrown** [comment]
I'm not sure what the exact implementation in React would be but when I've used d3 (including d3-dag) in Vue, I've done the d3 setup (`d3.select('container')`) in the lifecycle hook just after rendering (in Vue's case, the `mounted` hook, and i _think_ in React's case is `componentDidMount`).

**Comment by vaastav** [comment]
Hmm, do you have any open source examples I can look at that do that sort of setup with Vue? I can follow that and convert it to React then.
Thanks.

**Comment by znicholasbrown** [comment]
I don't have any open source examples to point to but this is what I'd do in a single-page Vue component (I dynamically assign IDs here as well):
```vue
<script>
import * as d3_base from 'd3'
import * as d3_dag from 'd3-dag'
import uniqueId from 'lodash.uniqueid'

// This just merges the two libraries together into one
// access point
const d3 = Object.assign({}, d3_base, d3_dag)

export default {
  data() {
    return {
      id: uniqueId('dag'),
      canvas: null
    }
  },
  mounted() {
    this.canvas = d3
        .select(`#${this.id}`)
        .attr('height', '100%')
        .attr('width', '100%')

    // Typical d3 logic can go here or in downstream methods
  }
}

</script>

<template>
  <svg :id="id" />
</template>
```

**Comment by erikbrinkman** [comment]
@vaastav I'm not really a webdev, so I can't really say what the appropriate thing to do is. With your, or someone else's help, I'm happy to look at what the desired goal would / how to implement it / just look at a PR, but otherwise UI know almost nothing.

**Comment by erikbrinkman** [comment]
As I've now picked up some react, but maybe not enough to see how a library should be useful. You could certainly put a dag node or a link into properties to help lay this out. Ultimately I think including react in this library is out of scope, and while I welcome someone to develop a library around this, I probably won't be doing it any time soon.
