### ISSUE TITLE
Constant separation?

### ISSUE THREAD

**Issue by BenPortner** [erikbrinkman/d3-dag#34]
Hi Erik,

I'm trying to figure out how to get constant spacing between neighboring nodes. When I have two nodes, they are positioned such that one is on the far left and the other is one the far right. As I add more nodes, the they move closer and closer together. At some point, they overlap. I want to prevent this. I would like to have the spacing independent of the number of nodes in a layer. I'd rather have the nodes move out of the screen when there are too many (it's not a problem because I have panning activated).

I'm using sugiyama layout like this:

> var tree = d3.sugiyama() 
    .size([height, width])
    .layering(d3.layeringSimplex())
    .decross(d3.decrossTwoLayer())
    .coord(d3.coordVert())
    .separation( (a, b) => { return 1 } );
`

I figured out that I can get constant separation between layers by setting 

>nodes.forEach(d => d.x = d.depth().layer * 140);

Is there something similar for the y-position?

Best regards
Ben

**Comment by erikbrinkman** [comment]
you should be able to use the [`nodeSize`](https://github.com/erikbrinkman/d3-dag#sugi_node_size) api to avoid both the retroactive `x` trick, and it should give you constant separation. I implemented it recently, and didn't test it extensively, so let me know how it works.

**Comment by BenPortner** [comment]
Works like a charm! Thanks a lot :)
