### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by chrismcgraw60** [erikbrinkman/d3-dag#35]
Hi,
This library is great. Are there any plans to release Typescript types for d3-dag?
Thanks.

**Comment by erikbrinkman** [comment]
As of v0.4.3 this has working typescript definitions. Let me know if you encounter errors or odd behavior. Getting typescript to honor union types as properties were added still seems strange ([see post](https://stackoverflow.com/questions/62669644/how-do-intersection-types-work-in-conjunction-with-polymorphic-this-and-generics)).
