### ISSUE TITLE
how to render

### ISSUE THREAD

**Issue by sauravanandb2w** [erikbrinkman/d3-dag#37]
as dag is generated using sugiyama how are we going to render it in HTML?

**Comment by znicholasbrown** [comment]
@sauravanandb2w since this is a d3 package, you can render however you'd like with d3! 

You can do something like this to render the nodes:

```javascript
svg.selectAll("circle")
  .data(dag.descendants())
  .join(
    enter =>
      enter
        .append("circle")
        .attr("cx", d => d.x)
        .attr("cy", d => d.y)
       // whatever other styling you want
  )
```

You'd do the same thing, maybe with a `path` using `dag.links()` to render the edges :)

**Comment by sauravanandb2w** [comment]
ohk, but how the curved edges are going to be rendered as svg has lines only...

**Comment by erikbrinkman** [comment]
If you look in the examples in the README, I have a few examples in observable like [this](https://observablehq.com/@erikbrinkman/d3-dag-sugiyama), where the curved edges are rendered using d3:

```js
const line = d3.line()
    .curve(d3.curveCatmullRom)
    .x(d => d.x)
    .y(d => d.y);
...
svgSelection.append('g')
    .selectAll('path')
    .data(dag.links())
    .enter()
    .append('path')
    .attr('d', ({ data }) => line(data.points))
```
