### ISSUE TITLE
node.count() counts leaves, not nodes

### ISSUE THREAD

**Issue by dbdr** [erikbrinkman/d3-dag#39]
The doc of node.count() in the readme says:

> Set the value of each node to be the number of descendants including itself.

However, it looks to me, from the behaviour and the code, that it counts the number of *leaves* among the descendants of the node.

**Comment by erikbrinkman** [comment]
You're correct! It's an error in the documentation. This is meant to mimic the output of [`d3-hierarchy's count()`](https://github.com/d3/d3-hierarchy#node_count)
