### ISSUE TITLE
Disconnected components in DAG

### ISSUE THREAD

**Issue by sebitokazu** [erikbrinkman/d3-dag#43]
Hi, is it possible to create the DAG with disconnected components but that still meet DAG's requirements? Or it must be a single connected component? (image representation: https://i.stack.imgur.com/CCoZ2.jpg)

**Comment by erikbrinkman** [comment]
Unfortunately it's not fully supported. You can create disconnected dags, but many layouts will not work properly with them. I know _how_ I want to fix it, but I'm still putting the finishing touches the migration to typescript. I think there's another open request that talks about the same issue, and I don't think it'll be too difficult to do, so I'll prioritize it next.

**Comment by BenPortner** [comment]
Wouldn't it be possible to simple make the edge to the disconnected part invisible?
