### ISSUE TITLE
Can't resolve 'javascript-lp-solver'

### ISSUE THREAD

**Issue by plouc** [erikbrinkman/d3-dag#5]
Hi @erikbrinkman,

Thank you for this library!
I'm trying to build components based on it for [nivo](https://github.com/plouc/nivo), however I had an error during build phase, `javascript-lp-solver` cannot be resolved as it's not defined as a dependency but as a dev dependency.

**Comment by plouc** [comment]
In fact it also applies to `fastpriorityqueue` and `quadprog-js`

**Comment by erikbrinkman** [comment]
I attempted to copy `d3-hierarchy`, which is why these were in devDependencies. I always thought it was odd, and it seems that that was just a poor decision, and the module hasn't been updated. About to submit a pr that fixes it.

**Comment by plouc** [comment]
Thank you!
