### ISSUE TITLE
Using d3-dag in angular

### ISSUE THREAD

**Issue by natrayanp** [erikbrinkman/d3-dag#50]
Getting the below error when i use d3-dag in Angular
--------------------------------------------

ERROR in ./node_modules/d3-dag/src/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/projects/ETL/newdrawnode/node_modules/d3-dag/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/projects/ETL/newdrawnode/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:949:23)
    at plugin.done.then (/home/projects/ETL/newdrawnode/node_modules/@ngtools/webpack/src/loader.js:43:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

--------------------------------------------

Tried this in tsconfig.ts, still the same error
 "files": ["/home/projects/ETL/newdrawnode/node_modules/d3-dag/src/index.ts"]

Any idea on how to resolve this?

**Comment by erikbrinkman** [comment]
I just published a new version that should have better typing. I'm not sure it 100% fits the angular format, but let me know what the new errors are, or if it just works.

**Comment by natrayanp** [comment]
Thank you.  Build successful with 0.4.6 version (in Angular 10).
