### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by jrwm** [erikbrinkman/d3-dag#54]
Hi, I am using your lib in a website built by Webpack. However the latest functional version is 0.4.1 on a specific commit hash. Otherwise the webpack build fails on `Module not found: Error: Can't resolve 'child_process'` and `Module not found: Error: Can't resolve 'fs'`. Should I try to fix it and send a Pull request or should I just fork the repo and maintain my paralel version of this project?

**Comment by erikbrinkman** [comment]
I'm already using a bundler to build it, and I think I remember these as warnings recently. If you can figure out why (likely a bundle configuration issue) I'll happily accept the pr, otherwise, I'll also look into it.

Thanks for reporting!

**Comment by jrwm** [comment]
The reason why it throws errors is because both `child_process` and `fs` are Node Core modules. Both won't work in a browser environment and that's why Webpack refuses to bundle them as they would increase the bundle size and wouldn't work anyway. Yeah, on one side, it's a matter of Webpack configuration but on the other hand, the correct way how to solve this, is modify source code of `d3-dag` so 'child_process` and `fs` aren't imported/required when using the library targeting a web.

**Comment by erikbrinkman** [comment]
Right, the problem is that d3-dag doesn't natively use fs or child process, they're used by dependencies that are required, so the solution is having the bundler shim them on platforms where they don't exist. I had something like that up before, but the bundle configuration is quite brittle, so I imagine some update broke the way that was working, and now they're not shimmed properly.

**Comment by erikbrinkman** [comment]
I think I just needed to move the plugins around. The packaged version [here ](https://we.tl/t-zgZ8bun4ib) should fix the problem. It's just a build of the `builtins` branch, if you'd prefer to build it yourself. I want you to verify that it works before I publish a new version.

**Comment by jrwm** [comment]
It compiles now, that's great 🎉
