### ISSUE TITLE
Spaces in ID field

### ISSUE THREAD

**Issue by labriola** [erikbrinkman/d3-dag#58]
At least using stratify, spaces in the id are unsupported and cause some confusion at the moment. 

There may be more than one place but guessing this is part of the culprit

stratify.id = id;

I would be happy to adjust and create a PR but, before I did, I wanted to make sure that this wasn't an intentional issue or something you would prefer left alone.

**Comment by erikbrinkman** [comment]
Thanks for the issue! In general, I'm happy to receive PRs. I just added a test to see if stratify works with spaces in ids, and it seems to. Could you be more specific with the error that you're having?

https://github.com/erikbrinkman/d3-dag/blob/2270106f8ecfa8713a1c2a674062b6c31c2b9eaa/test/dag/stratify.test.ts#L64-L68

**Comment by labriola** [comment]
Thanks for the quick reply. Agreed your test does seem to disprove my assertion. Give me a day or so to dig in as perhaps I am misdiagnosing where the problems actually exists. Thanks again for looking into this (and the work on this project in general). If you don't mind leaving this issue open a bit longer I will gather more information and report back

**Comment by labriola** [comment]
I am going to close this one; the issue is not here and I misdiagnosed it. 

In your example code (specifically the arrow example but perhaps others), when plotting the edges, an id is created for the gradient by concatenating the source.id and target.id with a - between.

That ID is later used to create a URL. It is here that the problem occurs as the resultant URL has spaces and hence any nodes with spaces appear not the be connected... but it is a plotting problem, not a data modeling problem. In either case, thank you again for the hard work. I was attempting to evolve your example with more complicated data to understand the relationships and frankly misinterpreted.

Cheers

**Comment by erikbrinkman** [comment]
Thanks for diagnosing, I'll update the examples with a note that the gradient ids aren't tolerant of spaces as written (or I guess I could just urlencode them)

**Comment by labriola** [comment]
Yeh, confirmed that encoding does 'fix' the issue but I don't think you need to update it with a note... this feels firmly in the camp of "These are examples, I can't cover all possibilities"

**Comment by erikbrinkman** [comment]
yeah, but I already updated them 😅. It wasn't that hard to wrap `gradId` in `encodeURIComponent`. If you find any other issues, bad examples, poor documentation etc, issues and PRs are always welcome!
