### ISSUE TITLE
Infinite layout

### ISSUE THREAD

**Issue by labriola** [erikbrinkman/d3-dag#59]
Adding this issue as I can (seemingly) cause infinite layout cycle in d3-dag using the following test data and configuration:

```
    const layout = d3.sugiyama()
      .layering(d3.layeringSimplex())
      .decross(d3.decrossOpt())
      .coord(d3.coordVert())
      .nodeSize((node) => {
        return [130, 130];
      })
```
I plan on attempting to debug further but thought, if nothing else, it might be useful to have the data for a future test. While I cannot confirm that this isn't some awful mistake on my part (made worse by the fact that this makes chrome go to the bad place _really_ fast so it's hard to test), I did confirm that the data is not infinitely recursive and is render-able through other DAG renders (e.g. dagitty)

Will post more here if I determine a root cause (including if it is me)

[dagData.txt](https://github.com/erikbrinkman/d3-dag/files/6412089/dagData.txt)

**Comment by erikbrinkman** [comment]
It's probably the fact that you're using optimal decrossing. That is very unperformant. From the documentation

> This method solves an np-complete integer program, and as such can take a very long time for large DAGs.

It currently has a check to see if the dag will crash the program, but maybe I should put in a check where it errors for anything other than a small dag.

If you are really interested in using optimal decrossing, there's probably not a lot you can do. However the current implementation is solving over a state space roughly `O(H 2^(W²))` which is much larger than the actual state space `O(H W!)` so it could be optimized a fair bit for medium sized dags.

**Comment by labriola** [comment]
Thanks for the reply. I certainly knew it might take a long while but was more interested to see if it will ever complete (which it has not yet). In either case, will play a bit with this and other option. As always, thanks for the hard work

**Comment by erikbrinkman** [comment]
Yeah, the problem with exponential growth is that cutoff is very steep. Will it ever finish? It should, there's a finite number of choices. it may take days or weeks though.

**Comment by labriola** [comment]
I am now at least a little amused at the idea of determining how long it takes. Perhaps a little empirical study on a second machine. Will close this one for now and maybe some future state I can help optimize
