### ISSUE TITLE
How do I represent a single node with `dagConnect`.

### ISSUE THREAD

**Issue by endrebak** [erikbrinkman/d3-dag#62]
I sometimes have graphs that only have one node, or only unrelated, disconnected nodes. How do I display these with the `dagConnect` reader?

If this is not possible, can I do it with `dagStratify`?

**Comment by erikbrinkman** [comment]
You're correct, you can't represent a single node with `dagConnect`. At least not currently, although if you have suggestions I'd be open to it. You can do it easily with either `dagStratify` or `dagHierarchy`. You just don't define any structure (parents or children depending on the constructor)

**Comment by endrebak** [comment]
I tried to do this with a node that connected to itself

```
["samtools-index" "samtools-index"]
```

and a one-element array/string

```
["bwa-map"]
"pyranges-merge"
```

Dunno if adding one or more of those options is a good idea. It means adding semantics to what is currently just data. And nothing prevents those nodes from having ancestors/parents anyways.

Perhaps a `dagConnectPossiblySingle` (need a better name) would work?

I think I should just use the existing APIs, but perhaps we can add a note to the `dagConnect` docs about this special case?

**Comment by erikbrinkman** [comment]
You should "now" (on master or next release) be able to do `dagConnect().single(true)(["samtools-index", "samtools-index"])` to create a single node.
