### ISSUE TITLE
404 to DAG Structure docs from README.md

### ISSUE THREAD

**Issue by curiouserrandy** [erikbrinkman/d3-dag#66]
The link from the readme (https://github.com/erikbrinkman/d3-dag/blob/main/README.md) under API Reference -> "DAG - documentation on the DAG structure" (https://erikbrinkman.github.io/d3-dag/interfaces/dag.dag-1.html) 404s.  

(Guessing it's a repository switch error, but the obvious transformations of erikbrinkman.github.io -> github.com/erikbrinkman didn't work for me, so I figured I'd toss you a note.)

**Comment by erikbrinkman** [comment]
It's actually an error with typedoc generating new urls. I'll update them. Thanks for pointing it out out!
