### ISSUE TITLE
Add nodes without computing the whole layout from scratch

### ISSUE THREAD

**Issue by uraniumreza** [erikbrinkman/d3-dag#72]
Hi @erikbrinkman; first of all, thank you so much for this awesome package.

I'm working with a DAG visualizer which consists of a large amount of nodes (>2/3K). And I was using this layout -
```javascript
const layout = d3
  .sugiyama()
  .size([this.width, this.height])
  .layering(d3.layeringSimplex())
  .decross(d3.decrossTwoLayer())
  .coord(d3.coordQuad());
```

As you can imagine for that amount of nodes, it's taking quite some time with `coordQuad()`; I tried `coordCenter()` and `coordGreedy`, they worked pretty fast but the graph doesn't look "okay"! So, I stuck to `coordQuad()` and trying other ways to optimize the whole layering.

I removed one layer of children (specific type) from the dag and the layering is done in reasonable time. Then, I wanted to enter those removed children in the existing dag, and without recomputing the whole thing, how can I make sure that the layering will follow the existing node positions and try to add those newly added nodes.

Hope I could give you an idea of what I'm trying to achieve here. Please let me know if you need any specifics from my code so that I can share one snippet with you.

**Comment by erikbrinkman** [comment]
@uraniumreza What you've described makes sense. I have a few questions to try and nail down the best path forward.

1. I've considered incremental layouts before. There's a github issue where I propose this. Unfortunately the initial requester wasn't willing to come up with a design of what incremental generation would look like, and I wasn't willing to try and design something I wasn't going to use.

   In your case though, I don't think this is a good solution. Like greedy not producing an optimal layout, if you try to mix incremental and quad you may end up with the same problems. I'm willing to walk down this path, but I don't think it is the best solution given what you've described, as you're only interested in incremental layouts for the speed benefit.
2. Do you really need / want to layout 3K nodes? Would it makes sense / be possible to layout "meta nodes," or some grouped representation of the dag? It seems like 3K would be hard to visualize, so this may be a solution / the best solution, but given that you're trying so hard I'm guessing you still want to lay them out fully. Basically I'm asking if this is really a problem. Alternatively there may be tricky things you can do, where you compute the layering and decross structure, but only compute the actual coordinates for what's visible. The library isn't currently set up to do this, and like 1, we'd need to actually design a proper api, but I think we could figure something out.
3. What was wrong with greedy? Greedy is much faster. I will admit it doesn't look super nice, but maybe running greedy in reverse and doing it as a two-pass will result in a better layout, and still faster than quad. I think this is probably the most promising, and would be willing to prototype different solutions with you to find a fast, reasonable looking layout, but it would help to have data / make sure this is the path you want to go down before diving too deep.
4. I've been playing around with rust and web assembly lately. A quadratic optimization is always going to be slow, but potentially web assembly can speed it up enough to get your case working. In my experiments, there's always been a problem with bundling for commonjs, so I haven't wanted to try and incorporate it, but depending on your usecase, I could work to publish a standalone coord operator that does coodQuad but in wasm. I don't know how much of a speedup this will offer, and it won't make coord quad scale indefinitely, but depending on your use-case, maybe it will speed it up enough.

Let me know what of this resonates most with you and why. Also, shing your data will help me prototype test things on my end.

**Comment by erikbrinkman** [comment]
closing in favor of discussions on #79
