### ISSUE TITLE
layeringCoffmanGraham results in incorrect reported total width

### ISSUE THREAD

**Issue by oliviercailloux** [erikbrinkman/d3-dag#74]
Do I understand correctly that calling [`layout`](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama.SugiyamaInfo.html) should report the total height and width?

It usually does just that, but when using the CoffmanGraham layering algorithm with a width that does not divide the total number of nodes, the reported width is incorrect (larger than actual width taken). Seems like the “phantom” nodes (that would make an equal number of nodes per layer) still count in the reported width.

Is this expected, or a bug? (I’d find convenient to know the actual total width taken by the layout.)

**Comment by erikbrinkman** [comment]
Hey @oliviercailloux . I'm not sure I entirely comprehend, but I'll see if I do.

You've been using the coffman-graham layering operator with a specified width that does does not divide the total number of nodes in the dag, and when you do this, the returned width computed by the layout is larger than you expect?

- In general, the "width" returned by the layout is the total width, including edges. Edges are computed using dummy (phantom) nodes, and every node in the layout has a width, so if the edges curve outside of the rest of the real nodes, the width will be larger than just that of the nodes themselves.
- As far as I can tell, setting the width of coffman-graham, or the width's relation to the total number of nodes should be irrelevant, however coffman-graham does tend to produce a lot of edges, so you're more likely to encounter this occurance under these conditions.

Does all of this fit with what you're experiencing? If so, would you want the ability to get the width without edges being taken into account? You should be able to roughly do this by just iterating over all of the nodes and offsetting their x by ± node_width/2. and taking the max / min of all of those values.

**Comment by oliviercailloux** [comment]
> You've been using the coffman-graham layering operator with a specified width that does does not divide the total number of nodes in the dag, and when you do this, the returned width computed by the layout is larger than you expect?

Exactly!

> In general, the "width" returned by the layout is the total width, including edges. Edges are computed using dummy (phantom) nodes, and every node in the layout has a width, so if the edges curve outside of the rest of the real nodes, the width will be larger than just that of the nodes themselves.

I am not sure I understand what a dummy node is here. In my OP I used the phrase phantom node to refer to the x nodes that must be added so that each layer has exactly w nodes inside, with w the width I chose as parameter value for the C⁻G layering. So if n is the number of (real) nodes in the graph, x is the smallest non-negative number such that w divides (n + x). But I think that your reply, and [this doc](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_coffman_graham.CoffmanGrahamOperator.html), refer to something else with the term “dummy node”.

> As far as I can tell, setting the width of coffman-graham, or the width's relation to the total number of nodes should be irrelevant, however coffman-graham does tend to produce a lot of edges, so you're more likely to encounter this occurance under these conditions.

If there are no dummy nodes, then this phenomenon cannot occur. Am I right? 

> would you want the ability to get the width without edges being taken into account?

Just to be sure that we are on the same page, do you mean here “the width without edges going to dummy nodes”? Do we agree that those nodes will not be represented in a typical plot of the graph, and, therefore, neither will these edges? And do we agree that this is thus the same as the width without dummy nodes being taken into account? If all three are positive, my answer is yes, that is the width I am interested in.

> You should be able to roughly do this by just iterating over all of the nodes and offsetting their x by ± node_width/2. and taking the max / min of all of those values.

Yes, thank you, that makes sense. But I would like to suggest to return precisely that number in the information that result from the call to `layout`. If I understand correctly, I do not see what the currently returned width can be used for. (I hope it is clear that I don’t want this to sound as a criticism, I just want to make sure we understand each other and, if so, propose a change in a constructive spirit.)

**Comment by erikbrinkman** [comment]
There's a lot to respond to, but I'll try to take everything in order. Also, this doesn't sound critical, you're ultimately spending effort to make this library better, so I appreciate it.

> I used the phrase phantom node to refer to the x nodes that must be added so that each layer has exactly w nodes inside, with w the width I chose as parameter value for the C⁻G layering.

The CG layering doesn't guarantee that there are `w` nodes in each layer, just no more than `w` nodes.

> Just to be sure that we are on the same page, do you mean here “the width without edges going to dummy nodes”? Do we agree that those nodes will not be represented in a typical plot of the graph, and, therefore, neither will these edges? 

Dummy nodes are a necessary aspect to the layout that will only be unnecessary if after the layering, the difference between the layer of every source and target node is one. Dummy nodes are used to layout the edges, so they are something that should get represented in a typical layout of the graph, but you'll only notice them if you look at the edge points. See the examples that render the edges from the README.

In general, if you don't want edges to have "thickness" you should set their width to zero, but if you're using a recent version, that is the default (unless you're overriding [nodeSize](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama.SugiyamaOperator.html#nodeSize), and then maybe it's not).

Casually looking at width's returned by CG don't seem out of the ordinary. If you're not ascribing large widths to dummy nodes (undefined values for nodeSize) then I'm not sure what would be causing this, and an example with data might help.

**Comment by oliviercailloux** [comment]
> The CG layering doesn't guarantee that there are `w` nodes in each layer, just no more than `w` nodes.

I understood that. Still, the quantity x that I defined is well-defined. 

I suppose that my notion of phantom nodes as I defined just above is, though well-defined, irrelevant to our discussion. So, a dummy node is not a phantom node. But I still fail to understand what a dummy node is.



> Dummy nodes are a necessary aspect to the layout that will only be unnecessary if after the layering, the difference between the layer of every source and target node is one. Dummy nodes are used to layout the edges, so they are something that should get represented in a typical layout of the graph, but you'll only notice them if you look at the edge points.

I absolutely do not understand what a dummy node is. What is an edge point, a point where an edge touches a node’s boundary?

> See the examples that render the edges from the README.

I just had another look at the [Sugiyama](https://observablehq.com/@erikbrinkman/d3-dag-sugiyama) example, chose the CG layering, and looked at the edge points. I still fail to understand what a dummy node is.

In [`NodeSizeAccessor`](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama.NodeSizeAccessor.html), a dummy node is described as “a piece of a long edge that can curve around other nodes”, which I do not understand either. What is a long edge?

> If you're not ascribing large widths to dummy nodes (undefined values for nodeSize) then I'm not sure what would be causing this

I am assigning a fixed size to every node, I think that this includes dummy nodes.

> an example with data might help

Agreed, this would be a practical way forward. Let’s stop the discussion about dummy nodes, which I don’t think is converging. I’ll see if I can come up with a short example (currently the logic of my code producing the graph is dispersed and not straightforward to isolate).

**Comment by erikbrinkman** [comment]
I think I can spare you some of the effort. Right now you're doing something like:
```
sugiyama().nodeSize(() => [nodeWidth, nodeHeight])...
```
correct?

try changing it to:
```
sugiyama().nodeSize(node => node === undefined ? [0, 0] : [nodeWidth, nodeHeight])...
```

Hopefully this correction will work. If it does, I should probably improve the documentation around `nodeSize`. I'm sorry this has been as frustrating as it seems like it has. Read on for a more detailed explanation of the algorithm and how it relates to this. IF you want to suggest how the documentation should be improved, I'm all ears / PRs welcome!

Here's how the sugiyama layout algorithm works:
1. Assign an integer layer to each node such that children have a higher layer than their parent.
2. Add summy nodes along each edge where the difference between parent and child layer is more than one, such that now you have a layered dag where each edge goes from one layer to the next.
3. Reorder the nodes in each layer to minimize crossings
4. Assign x coordinates to each node in a layer to respect node sizes and ordering (Note that nodes here may be dummy nodes)
5. Remove the dummy nodes, storing their positions in the edge information.

I can demonstrate this with a simple dag. Imagine `a -> b, a -> c, b -> c`. How should this be laid out? A natural way would be something like:
```
a
|\
b |
|/
c
```
note that here, the edge from `a -> c` has to "curve around" b. The layout does this by actually putting a dummy node in the graph so instead it looks like:
```
a
|\
b o
|/
c
```
Now all edge are straight, only span one layer, and easy to "work with". When you set a constant nodeSize, you actually gave that node, which represented a "long edge" a size, and that caused the layout to go crazy. When you call nodeSize, those are passed as undefined values. The relevant attribute of the final layout is the `points` attribute of a `link` accessed usually by the `links` method. In this example, the link would have a point indicating its curve. If you're not using the points in links, then you probably won't see that your edges are actually curving around your nodes, but the layout thinks they should be.

**Comment by oliviercailloux** [comment]
Thanks a lot. This solves the problem indeed. So this is not a bug.

The whole problem is just that I had a hard time understanding what a dummy node is.

>     Add [d]ummy nodes along each edge where the difference between parent and child layer is more than one, such that now you have a layered dag where each edge goes from one layer to the next.

This is the definition of dummy nodes I was missing. I suggest to add this somewhere, perhaps where CG layering is explained.

**Comment by erikbrinkman** [comment]
This actually has nothing to do with CG, it's part of the layout, but CG is probably affected by it the most, since as you constrain the width, you naturally get more edges.

I'm going to reopen this, just as a reminder to update the documentation.
