### ISSUE TITLE
Webpack error during build : Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by guy-j** [erikbrinkman/d3-dag#82]
Hello,

Thanks for your work on this library, it is very useful for d3 beginners !
I am currently using this library indirectly (through [React D3 DAG](https://github.com/forivall/react-d3-dag)) and I get thinks done quite OK but I have a build time issue with webpack (with create-react-app) : 

WARNING in ./node_modules/d3-dag/bundle/d3-dag.esm.min.js 14:44-54
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/data/project_test/node_modules/webpack/lib/dependencies/ContextDependency.js:91:18)
    at Compilation.reportDependencyErrorsAndWarnings (/data/project_test/node_modules/webpack/lib/Compilation.js:3129:24)
    at /data/project_test/node_modules/webpack/lib/Compilation.js:2726:28
    at _next2 (eval at create (/data/project_test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at eval (eval at create (/data/project_test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at /data/project_test/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:385:11
    at /data/project_test/node_modules/neo-async/async.js:2830:7
    at Object.each (/data/project_test/node_modules/neo-async/async.js:2850:39)
    at /data/project_test/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:361:18
    at /data/project_test/node_modules/neo-async/async.js:2830:7
 @ ./src/components/Simulation/Diagram/diagram.component.tsx 16:0-32 214:16-33 216:19-33 217:13-29
 @ ./src/components/Simulation/SimulationDetail/simulation.detail.component.tsx 26:0-51 1396:39-46
 @ ./src/App.jsx 17:0-100 506:91-107
 @ ./src/AppWithProviders.jsx 11:0-24 76:41-44
 @ ./src/index.js 6:0-50 9:38-54

I tried versions 0.8.2 and 0.9.1 but still the same issue. Do you have any clue ? Did you ever encounter this issue ?

Cheers
Jérémie

**Comment by erikbrinkman** [comment]
This is strange, and unfortunately I've never seen it before.

The first thing I would try is to see if you can change the imports from `import ... from "d3-dag"` to `import ... from "d3-dag/dist/index"`. That should import the unbundled version of d3-dag, which may fix the problem entirely.

Otherwise providing a MWE git repo or setup to trigger this would help too. Sorry I can't be of more immediate help

**Comment by guy-j** [comment]
Thanks for the quick reply, unfortunately as I am using it through `react-d3-dag` I cannot update the import directly in my project as it is already packaged with `d3-dag` bundle inside... As I do not see issues tab in `react-d3-dag` I will try to fork it when I have a chance to try your trick and let you know.

As far as I know from stackoverflow and google, it might be linked to a dynamic usage of `require`.

Cheers,
Jérémie

**Comment by guy-j** [comment]
Hi,

So I have cleaned my deps (cause I was trying to install `d3-dag` with another version alongside of `react-d3-dag`) and reinstalled again. I have changed every imports in `react-d3-dag` from "d3-dag" to "d3-dag/dist/index" as you said, and this time the build did not complain anymore with the warning ! Thanks. I would like to avoid the webpack plugin for production build if I can, so maybe upgrading `react-d3-dag` to use `d3-dag@0.9.1` would fix it ? I will make a PR there although I am not able to test it locally here...

Cheers,
Jérémie

**Comment by erikbrinkman** [comment]
Good to know it's an issue with bundling. You should also be able to to go into react-d3-dag and just update the version in their package.json. Not much broke between 08 and 0.9, so I'd be shocked if it didn't work.

If you want something more reusable you could also always clone react-d3-dag locally, update the deps, and change your package.json to `"react-d3-dag": "file:..<path to clone"`. If that works, it should be easy to se up a PR for them to update.

Sorry I'm doing more to actually help with this, but without an example, and with issues turned off on `react-d3-dag` I'm not sure how to do more.

**Comment by guy-j** [comment]
Yes I created a fork and upgraded to d3-dag@0.9.1, it seems to be solving the issue. Just checking if I did not break anything in tests or linting... I still need to publish the PR and I hope the maintainer will be reactive :)

**Comment by erikbrinkman** [comment]
Seems like there's nothing I can do then, as this was indeed fixed in `0.9.1`. You can point to the [changelog](https://github.com/erikbrinkman/d3-dag#updating-from-08-to-09) in your PR if that helps. I'm going to close this for now, but if you find any other issues or want me to weigh on the other PR, don't hesitate to ask.

Thinking more, I guess I could potentially try to back out the fix to `0.8.3` but that seems like more work then necessary, so I'm going to hold off until seeing that it's not an issue.

**Comment by guy-j** [comment]
Thanks for your help, I have published a PR on react-d3-dag for this : https://github.com/forivall/react-d3-dag/pull/1
