### ISSUE TITLE
Dynamic nodeSize?

### ISSUE THREAD

**Issue by duongthienlee** [erikbrinkman/d3-dag#86]
Thank you for the great library. This is not an issue, just for you know. It's more like a question to ask whether you have plan to support dynamic node size.
I know this library is built to mimic d3-hierarchy, even though d3-hierarchy doesn't support dynamic node size. Having it in this library would be useful.

**Comment by erikbrinkman** [comment]
Yeah, most layout operators have a `nodeSize` argument that allows you to specify the size of the node.

For simplicity, nodes are densely packed so you usually want to add some padding to that. The `sugiyama` method also has some special quirks so make sure you read the documentation.
